# Generated by Django 5.1.2 on 2025-02-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportVirusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_no', models.CharField(max_length=100)),
                ('organism_name', models.CharField(max_length=200)),
                ('vrl', models.CharField(blank=True, max_length=50, null=True)),
                ('isolate', models.CharField(blank=True, max_length=200, null=True)),
                ('species', models.CharField(max_length=200)),
                ('length', models.IntegerField()),
                ('geo_location', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
